#!/usr/bin/perl
#
# An unit test for the geni-automerge script.
#
# Usage: ./unit_test - for listing all the tests with results.
#        prove unit_test - for a shorter output.
#
use strict;
use Test::Builder;

our $CALLED_BY_TEST_SCRIPT = 1;

require "geni-automerge.pl";

my $Test = Test::Builder->new;

init();

$Test->ok(numbersInRange("1200", "1200"), "identical years");
$Test->ok(!numbersInRange("1200", "1201"), "Adjacent no circa");
$Test->ok(numbersInRange("1200", "1201", 1, 2), "Adjacent with circa");
$Test->ok(!numbersInRange("1200", "1203", 1, 2), "Adjacent too far apart");


$Test->done_testing();
